---
title: ""
output: github_document
---


```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = TRUE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               # fig.width = 8.64,
               # fig.height = 4.86,
               fig.path = 'figures/')
```


```{r}
# Load packages
library(tidyverse)
library(raster)
library(ggthemes)
library(ggrepel)
```

```{r}
# Get Mozambique data
moz1 <- getData(country = 'MOZ', level = 1)
# Trim the columns
moz1@data <- moz1@data %>% dplyr::select(GID_0, NAME_0, NAME_1) %>% mutate(country = 'Mozambique')
# Get neighboring country data 
tza0 <- getData(country = 'TZA', level = 0)
zaf0 <- getData(country = 'ZAF', level = 0)
swz0 <- getData(country = 'SWZ', level = 0)
zwe0 <- getData(country = 'ZWE', level = 0)
mwi0 <- getData(country = 'MWI', level = 0)
zmb0 <- getData(country = 'ZMB', level = 0)
# Make the neighboring data combinable with the Mozambique data (and add a placeholder NAME_1 column)
tza0@data <- tza0@data %>% mutate(NAME_1 = 'Tanzania', country = 'Other')
zaf0@data <- zaf0@data %>% mutate(NAME_1 = 'South Africa', country = 'Other')
swz0@data <- swz0@data %>% mutate(NAME_1 = 'Eswatini', country = 'Other')
zwe0@data <- zwe0@data %>% mutate(NAME_1 = 'Zimbabwe', country = 'Other')
mwi0@data <- mwi0@data %>% mutate(NAME_1 = 'Malawi', country = 'Other')
zmb0@data <- zmb0@data %>% mutate(NAME_1 = 'Zambia', country = 'Other')

# Combine
combined <- rbind(tza0, zaf0, swz0, zwe0, mwi0, zmb0)

# Make data into long format
combined <- fortify(combined, region = 'NAME_1')
moz_fortified <- fortify(moz1, region = 'NAME_1')
```

```{r}
# Define the colors for the Mozambican provinces
cols <- colorRampPalette(RColorBrewer::brewer.pal(n = 9, name = 'RdYlBu'))(20)
cols <- cols[5:(5+length(unique(moz_fortified$id)))]

# Define the coordinates for plotting the province names
coords <- coordinates(moz1)
coords <- data.frame(coords)
names(coords) <- c('long', 'lat')
coords$label <- moz1@data$NAME_1
# Make some manual adjustments for aesthetic purposes
coords <- coords %>% filter(label != 'Maputo City')
coords$lat[coords$label == 'Manica'] <- -17.9
coords$lat[coords$label == 'Sofala'] <- -20
coords$lat[coords$label == 'Nassa'] <- -13.5
coords$lat[coords$label == 'Gaza'] <- -24
# Make two words on two lines (Cabo Delgado)
coords$label <- gsub(' ', '\n', coords$label)


# Plot
ggplot() +
  geom_polygon(data = moz_fortified, 
               aes(fill = id,
                   group = group,
                   x = long,
                   y = lat),
               color = 'black',
               lwd = 0.1) +
  geom_text(data = coords,
            aes(x = long,
                y = lat,
                label = label),
            alpha = 0.6) +
  scale_fill_manual(name = '',
                    values = cols) +
  geom_polygon(data = combined,
               aes(group = group,
                   x = long,
                   y = lat),
               fill = 'tan',
               color = 'black', 
               alpha = 0.6,
               lwd = 0.1) +
  coord_map(xlim = c(30, 43),
                  ylim = c(-27, -10.5)) +
  theme_map() +
  theme(legend.position = 'none') 
```

Version highlighting Maputo province

```{r}
# Identify which index is Maputo province
index <- which(sort(unique(moz_fortified$id)) == 'Maputo')
# Modify the colors accordingly
cols[index] <- 'red'
# Plot
ggplot() +
  geom_polygon(data = moz_fortified, 
               aes(fill = id,
                   group = group,
                   x = long,
                   y = lat),
               color = 'black',
               lwd = 0.1) +
  geom_text(data = coords,
            aes(x = long,
                y = lat,
                label = label),
            alpha = 0.6) +
  scale_fill_manual(name = '',
                    values = cols) +
  geom_polygon(data = combined,
               aes(group = group,
                   x = long,
                   y = lat),
               fill = 'tan',
               color = 'black', 
               alpha = 0.6,
               lwd = 0.1) +
  coord_map(xlim = c(30, 43),
                  ylim = c(-27, -10.5)) +
  theme_map() +
  theme(legend.position = 'none') 
```